import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import Icon from "../components/Icon";
import { api } from "../lib/api";
import type { Appointment } from "../types";
const today=()=>new Date().toISOString().slice(0,10);const empty={customer_name:"",phone:"",vehicle:"",plate:"",service:"",scheduled_at:`${today()}T08:00`,status:"scheduled",notes:""};
export default function AgendaOficina(){const [params,setParams]=useSearchParams();const [date,setDate]=useState(today());const [items,setItems]=useState<Appointment[]>([]);const [form,setForm]=useState(empty);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const modal=params.has("novo");const load=()=>api.listAppointments(date).then(setItems).catch(e=>setError(String(e)));useEffect(()=>{void load()},[date]);useEffect(()=>{if(modal)setForm({...empty,scheduled_at:`${date}T08:00`})},[modal,date]);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await api.saveAppointment(form);setParams({});load()}catch(x){setError(String(x))}finally{setBusy(false)}};
 return <div className="page-enter"><div className="section-heading"><div><h2>Agenda da oficina</h2><p>Organize os horários e a capacidade de atendimento</p></div><button className="primary-action" onClick={()=>setParams({novo:"1"})}><Icon name="plus" size={18}/>Novo agendamento</button></div><div className="agenda-toolbar"><button onClick={()=>setDate(today())}>Hoje</button><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><div><strong>{new Date(`${date}T12:00`).toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}</strong><span>{items.length} agendamento{items.length!==1&&"s"}</span></div></div><div className="schedule-panel"><div className="time-rail">{Array.from({length:11},(_,i)=>i+7).map(h=><span key={h}>{String(h).padStart(2,"0")}:00</span>)}</div><div className="schedule-list">{items.length===0?<div className="large-empty"><span><Icon name="calendar" size={30}/></span><h3>Agenda livre neste dia</h3><p>Adicione um horário para reservar a entrada de um veículo.</p><button className="primary-action" onClick={()=>setParams({novo:"1"})}>Agendar serviço</button></div>:items.map(a=><div className={`appointment-card ${a.status}`} key={a.id}><time>{a.scheduled_at.slice(11,16)}</time><div className="appointment-icon"><Icon name="car"/></div><div><strong>{a.customer_name}</strong><span>{a.vehicle} {a.plate&&`· ${a.plate}`}</span><p>{a.service}</p></div><span className="appointment-status">{a.status==="scheduled"?"Agendado":a.status==="confirmed"?"Confirmado":a.status==="arrived"?"Veículo recebido":a.status}</span><a href={`https://wa.me/55${a.phone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">WhatsApp</a></div>)}</div></div>
 {modal&&<div className="modal-backdrop"><form className="workshop-modal" onSubmit={submit}><div className="modal-head"><div><h3>Novo agendamento</h3><p>Reserve um horário na agenda</p></div><button type="button" onClick={()=>setParams({})}><Icon name="x"/></button></div><div className="form-grid"><label className="full">Nome do cliente<input required autoFocus value={form.customer_name} onChange={e=>setForm({...form,customer_name:e.target.value})}/></label><label>Telefone / WhatsApp<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Data e hora<input required type="datetime-local" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></label><label>Veículo<input value={form.vehicle} onChange={e=>setForm({...form,vehicle:e.target.value})} placeholder="Marca e modelo"/></label><label>Placa<input value={form.plate} onChange={e=>setForm({...form,plate:e.target.value.toUpperCase()})}/></label><label className="full">Serviço solicitado<input required value={form.service} onChange={e=>setForm({...form,service:e.target.value})} placeholder="Ex.: Revisão preventiva"/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="scheduled">Agendado</option><option value="confirmed">Confirmado</option><option value="arrived">Veículo recebido</option></select></label><label className="full">Observações<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-action" onClick={()=>setParams({})}>Cancelar</button><button disabled={busy} className="primary-action">{busy?"Agendando...":"Salvar agendamento"}</button></div></form></div>}
 </div>}
