import { useEffect, useMemo, useState } from "react";
import Icon from "../components/Icon";
import { supabaseApi, type AdminLicense } from "../lib/supabase";
import { useSeller } from "../components/SellerGate";

const formatDate=(value:string|null)=>value?new Date(value).toLocaleDateString("pt-BR"):"Sem vencimento";
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const onlineWindow=8*60*1000;
const isOnline=(value:string)=>Boolean(value&&Date.now()-new Date(value).getTime()<onlineWindow);
type Summary={total:number;active:number;expired:number;revoked:number;paid:number;overdue:number;pending:number;monthly_revenue:number};
const zero:Summary={total:0,active:0,expired:0,revoked:0,paid:0,overdue:0,pending:0,monthly_revenue:0};

export default function Licencas(){
 const{sellerPassword}=useSeller();const[licenses,setLicenses]=useState<AdminLicense[]>([]);const[summary,setSummary]=useState<Summary>(zero);const[loading,setLoading]=useState(true);const[search,setSearch]=useState("");const[status,setStatus]=useState("");const[showNew,setShowNew]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");const[form,setForm]=useState({name:"",days:"30",notes:""});
 const derive=(items:AdminLicense[]):Summary=>({total:items.length,active:items.filter(x=>x.status==="active"&&(!x.expires_at||Date.parse(x.expires_at)>Date.now())).length,expired:items.filter(x=>Boolean(x.expires_at&&Date.parse(x.expires_at)<=Date.now())).length,revoked:items.filter(x=>x.status==="revoked").length,paid:items.filter(x=>x.billing_status==="paid").length,overdue:items.filter(x=>x.billing_status==="overdue").length,pending:items.filter(x=>!x.billing_status||x.billing_status==="pending").length,monthly_revenue:items.filter(x=>x.billing_status==="paid"&&x.last_payment_at?.slice(0,7)===new Date().toISOString().slice(0,7)).length*29.99});
 const load=async(silent=false)=>{if(!silent)setLoading(true);setError("");try{const rows=await supabaseApi.adminListLicenses(sellerPassword);setLicenses(rows);try{setSummary(await supabaseApi.adminLicenseDashboard())}catch{setSummary(derive(rows))}}catch(e){setError(e instanceof Error?e.message:String(e))}finally{if(!silent)setLoading(false)}};
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),30000);return()=>window.clearInterval(timer)},[]);
 const flash=(value:string)=>{setMessage(value);window.setTimeout(()=>setMessage(""),3500)};const fail=(e:unknown)=>setError(e instanceof Error?e.message:String(e));
 const create=async()=>{if(!form.name.trim())return setError("Informe o nome do cliente.");setBusy(true);setError("");try{const days=Number(form.days);const expires=new Date(Date.now()+days*86400000).toISOString();const created=await supabaseApi.adminCreateLicense(sellerPassword,form.name.trim(),"",10,expires,form.notes.trim());setForm({name:"",days:"30",notes:""});setShowNew(false);flash(`Licença criada: ${created.key}`);await navigator.clipboard?.writeText(created.key).catch(()=>{});await load()}catch(e){fail(e)}finally{setBusy(false)}};
 const toggle=async(item:AdminLicense)=>{try{await supabaseApi.adminSetLicenseStatus(sellerPassword,item.id,item.status==="active"?"revoked":"active");flash(item.status==="active"?"Licença revogada.":"Licença reativada.");await load()}catch(e){fail(e)}};
 const extend=async(item:AdminLicense)=>{const input=prompt("Prorrogar por quantos dias?","30");const days=Number(input);if(!input||!Number.isFinite(days)||days<=0)return;const base=item.expires_at&&Date.parse(item.expires_at)>Date.now()?new Date(item.expires_at):new Date();base.setDate(base.getDate()+days);try{await supabaseApi.adminExtendLicense(sellerPassword,item.id,base.toISOString());flash(`Vencimento alterado para ${formatDate(base.toISOString())}.`);await load()}catch(e){fail(e)}};
 const remove=async(item:AdminLicense)=>{if(!confirm(`Excluir definitivamente a licença de ${item.customer_name}?`))return;try{await supabaseApi.adminDeleteLicense(sellerPassword,item.id);flash("Licença excluída.");await load()}catch(e){fail(e)}};
 const removeMachine=async(id:string)=>{if(!confirm("Remover este computador do histórico da licença?"))return;try{await supabaseApi.adminDeleteActivation(sellerPassword,id);flash("Computador removido.");await load()}catch(e){fail(e)}};
 const copy=(key:string)=>{void navigator.clipboard?.writeText(key);flash("Chave copiada.")};
 const filtered=useMemo(()=>licenses.filter(x=>{const expired=Boolean(x.expires_at&&Date.parse(x.expires_at)<=Date.now());const state=x.status==="revoked"?"revoked":expired?"expired":x.status;return(!status||state===status)&&`${x.customer_name} ${x.customer_email} ${x.key}`.toLowerCase().includes(search.toLowerCase())}),[licenses,search,status]);
 return <div className="license-admin page-enter">
  <div className="license-heading"><div><span className="admin-kicker"><Icon name="tool" size={14}/> CENTRAL ADMINISTRATIVA</span><h2>Gerenciamento de licenças</h2><p>Acesso exclusivo de conversarcomgabriel@gmail.com</p></div><div><button className="secondary-action" onClick={()=>void load()}><Icon name="arrow" size={15}/>Atualizar</button><button className="primary-action" onClick={()=>setShowNew(true)}><Icon name="plus" size={17}/>Nova licença</button></div></div>
  <section className="license-metrics"><AdminMetric label="Licenças ativas" value={summary.active} detail={`${summary.total} cadastradas`} tone="green" icon="check"/><AdminMetric label="Vencidas" value={summary.expired} detail={`${summary.overdue} mensalidades atrasadas`} tone="orange" icon="alert"/><AdminMetric label="Pagas no sistema" value={summary.paid} detail={`${summary.pending} aguardando pagamento`} tone="blue" icon="wallet"/><AdminMetric label="Receita no mês" value={money(summary.monthly_revenue)} detail="Pagamentos confirmados" tone="purple" icon="chart"/></section>
  {message&&<div className="admin-notice success"><Icon name="check"/>{message}</div>}{error&&<div className="admin-notice error"><Icon name="alert"/>{error}</div>}
  <div className="license-toolbar"><label className="search-field"><Icon name="search" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por cliente, e-mail ou chave..."/></label><div className="filter-tabs compact">{[["","Todas"],["active","Ativas"],["expired","Vencidas"],["revoked","Revogadas"]].map(([v,l])=><button key={v} className={status===v?"active":""} onClick={()=>setStatus(v)}>{l}</button>)}</div></div>
  <section className="license-list">{loading?<div className="large-empty"><span><Icon name="clock"/></span><h3>Carregando licenças...</h3></div>:filtered.length===0?<div className="large-empty"><span><Icon name="clipboard"/></span><h3>Nenhuma licença encontrada</h3><p>Crie uma licença para liberar o primeiro cliente.</p></div>:filtered.map(item=>{const expired=Boolean(item.expires_at&&Date.parse(item.expires_at)<=Date.now());const label=item.status==="revoked"?"Revogada":expired?"Vencida":"Ativa";return <article className="license-row" key={item.id}><div className={`license-state ${item.status==="revoked"||expired?"danger":"ok"}`}><Icon name={item.status==="revoked"||expired?"alert":"check"}/></div><div className="license-customer"><strong>{item.customer_name||"Cliente sem nome"}</strong><span>{item.customer_email||"Aguardando primeiro acesso"}</span><button onClick={()=>copy(item.key)}><code>{item.key}</code> Copiar</button></div><div className="license-cell"><span>Status</span><b className={`status-chip ${item.status==="revoked"||expired?"canceled":"ready"}`}>{label}</b></div><div className="license-cell"><span>Mensalidade</span><b>{item.billing_status==="paid"?"Paga":item.billing_status==="overdue"?"Vencida":"Pendente"}</b></div><div className="license-cell"><span>Vencimento</span><b>{formatDate(item.expires_at)}</b></div><div className="license-cell"><span>Equipe</span><b>até {item.max_users||10} contas</b></div><div className="license-actions"><button onClick={()=>void extend(item)}>Prorrogar</button><button onClick={()=>void toggle(item)}>{item.status==="active"?"Revogar":"Reativar"}</button><button className="danger" onClick={()=>void remove(item)}>Excluir</button></div>{item.activations?.length>0&&<details><summary>{item.activation_count} computador{item.activation_count!==1&&"es"} registrado{item.activation_count!==1&&"s"}</summary><div>{item.activations.map(machine=><div className="machine-row" key={machine.id}><i className={isOnline(machine.last_seen_at)?"online":""}/><span><strong>{machine.machine_name||"Computador sem nome"}</strong><small>{machine.machine_id}</small></span><em>{isOnline(machine.last_seen_at)?"Online":"Offline"}</em><button onClick={()=>void removeMachine(machine.id)}>Remover</button></div>)}</div></details>}</article>})}</section>
  {showNew&&<div className="modal-backdrop"><div className="workshop-modal"><div className="modal-head"><div><h3>Nova licença</h3><p>A chave será copiada automaticamente após a criação</p></div><button onClick={()=>setShowNew(false)}><Icon name="x"/></button></div><div className="form-grid"><label className="full">Nome do cliente<input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome da oficina ou responsável"/></label><label>Validade inicial<select value={form.days} onChange={e=>setForm({...form,days:e.target.value})}><option value="30">30 dias</option><option value="90">90 dias</option><option value="180">180 dias</option><option value="365">1 ano</option></select></label><label className="full">Observações<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="modal-actions"><button className="secondary-action" onClick={()=>setShowNew(false)}>Cancelar</button><button disabled={busy} className="primary-action" onClick={()=>void create()}>{busy?"Criando...":"Criar licença"}</button></div></div></div>}
 </div>
}
function AdminMetric({label,value,detail,tone,icon}:{label:string,value:string|number,detail:string,tone:string,icon:Parameters<typeof Icon>[0]["name"]}){return <div className="metric-card"><span className={`metric-icon ${tone}`}><Icon name={icon}/></span><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></div>}
