import { useEffect, useMemo, useState } from "react";
import Icon from "../components/Icon";
import { api } from "../lib/api";
import type { ServiceOrder } from "../types";
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const labels:Record<string,string>={draft:"Orçamentos",approved:"Aprovadas",in_progress:"Em execução",waiting_parts:"Aguardando peça",ready:"Prontas",delivered:"Entregues",canceled:"Canceladas"};
export default function RelatoriosOficina(){const[orders,setOrders]=useState<ServiceOrder[]>([]);useEffect(()=>{api.listServiceOrders("","").then(setOrders).catch(console.error)},[]);const delivered=orders.filter(o=>o.status==="delivered");const revenue=delivered.reduce((s,o)=>s+o.total,0);const parts=delivered.reduce((s,o)=>s+o.parts_total,0);const labor=delivered.reduce((s,o)=>s+o.labor_total,0);const counts=useMemo(()=>Object.entries(labels).map(([key,label])=>({key,label,value:orders.filter(o=>o.status===key).length})),[orders]);const max=Math.max(1,...counts.map(x=>x.value));
return <div className="page-enter"><div className="section-heading"><div><h2>Relatórios da oficina</h2><p>Indicadores de produtividade e faturamento das ordens de serviço</p></div></div><section className="metric-grid"><Card title="Faturamento realizado" value={money(revenue)} icon="wallet" tone="green"/><Card title="Mão de obra" value={money(labor)} icon="tool" tone="orange"/><Card title="Peças aplicadas" value={money(parts)} icon="box" tone="blue"/><Card title="Ticket médio" value={money(delivered.length?revenue/delivered.length:0)} icon="chart" tone="purple"/></section><div className="dashboard-columns"><section className="panel report-panel"><div className="panel-head"><div><h3>Ordens por etapa</h3><p>Distribuição atual do fluxo de trabalho</p></div></div><div className="status-bars">{counts.map(x=><div key={x.key}><div><span>{x.label}</span><strong>{x.value}</strong></div><i><b style={{width:`${x.value/max*100}%`}}/></i></div>)}</div></section><section className="panel report-panel"><div className="panel-head"><div><h3>Resumo operacional</h3><p>Visão consolidada</p></div></div><div className="report-summary"><div><span>Ordens cadastradas</span><strong>{orders.length}</strong></div><div><span>Ordens entregues</span><strong>{delivered.length}</strong></div><div><span>Valor em aberto</span><strong>{money(orders.filter(o=>!["delivered","canceled"].includes(o.status)).reduce((s,o)=>s+o.total,0))}</strong></div><div><span>Taxa de conclusão</span><strong>{orders.length?Math.round(delivered.length/orders.length*100):0}%</strong></div></div></section></div></div>}
function Card({title,value,icon,tone}:{title:string,value:string,icon:Parameters<typeof Icon>[0]["name"],tone:string}){return <div className="metric-card"><span className={`metric-icon ${tone}`}><Icon name={icon}/></span><div><p>{title}</p><strong>{value}</strong><small>Com base nas ordens entregues</small></div></div>}
