import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import Icon from "../components/Icon";
import { api } from "../lib/api";
import type { Customer, Vehicle } from "../types";

const empty={customer_id:null as number|null,plate:"",brand:"",model:"",year:"",color:"",mileage:0,notes:""};
export default function Veiculos(){const [params,setParams]=useSearchParams();const [items,setItems]=useState<Vehicle[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [search,setSearch]=useState("");const [form,setForm]=useState(empty);const [edit,setEdit]=useState<number|undefined>();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const modal=params.has("novo")||params.has("editar");
 const load=()=>api.listVehicles(search).then(setItems).catch(e=>setError(String(e)));useEffect(()=>{void load()},[search]);useEffect(()=>{api.listCustomers("").then(setCustomers).catch(console.error)},[]);useEffect(()=>{const id=Number(params.get("editar"));const found=items.find(x=>x.id===id);if(found){setEdit(id);setForm({customer_id:found.customer_id,plate:found.plate,brand:found.brand,model:found.model,year:found.year,color:found.color,mileage:found.mileage,notes:found.notes})}else if(params.has("novo")){setEdit(undefined);setForm(empty)}},[params,items]);
 const close=()=>{setParams({});setError("")};const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await api.saveVehicle(form,edit);close();load()}catch(x){setError(x instanceof Error?x.message:String(x))}finally{setBusy(false)}};
 return <div className="page-enter"><div className="section-heading"><div><h2>Veículos</h2><p>Histórico e informações dos veículos atendidos</p></div><button className="primary-action" onClick={()=>setParams({novo:"1"})}><Icon name="plus" size={18}/>Cadastrar veículo</button></div><div className="toolbar-card"><label className="search-field"><Icon name="search" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por placa, modelo ou cliente..."/></label><span>{items.length} veículo{items.length!==1&&"s"}</span></div>
 <div className="data-panel">{items.length===0?<div className="large-empty"><span><Icon name="car" size={30}/></span><h3>Nenhum veículo cadastrado</h3><p>Cadastre o primeiro veículo para começar a criar ordens de serviço.</p><button className="primary-action" onClick={()=>setParams({novo:"1"})}><Icon name="plus"/>Cadastrar veículo</button></div>:<table className="workshop-table"><thead><tr><th>Veículo</th><th>Placa</th><th>Cliente</th><th>Ano / cor</th><th>Quilometragem</th><th/></tr></thead><tbody>{items.map(v=><tr key={v.id}><td><div className="table-entity"><span><Icon name="car" size={18}/></span><div><strong>{v.brand} {v.model}</strong><small>{v.notes||"Sem observações"}</small></div></div></td><td><b className="plate">{v.plate}</b></td><td>{v.customer_name||<em>Não vinculado</em>}</td><td>{[v.year,v.color].filter(Boolean).join(" · ")||"—"}</td><td>{v.mileage.toLocaleString("pt-BR")} km</td><td><button className="table-action" onClick={()=>setParams({editar:String(v.id)})}>Editar</button></td></tr>)}</tbody></table>}</div>
 {modal&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="workshop-modal" onSubmit={submit}><div className="modal-head"><div><h3>{edit?"Editar veículo":"Cadastrar veículo"}</h3><p>Preencha os dados de identificação</p></div><button type="button" onClick={close}><Icon name="x"/></button></div><div className="form-grid"><label className="full">Cliente<select value={form.customer_id??""} onChange={e=>setForm({...form,customer_id:e.target.value?Number(e.target.value):null})}><option value="">Sem cliente vinculado</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Placa<input required autoFocus value={form.plate} maxLength={8} onChange={e=>setForm({...form,plate:e.target.value.toUpperCase()})} placeholder="ABC1D23"/></label><label>Marca<input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})} placeholder="Ex.: Volkswagen"/></label><label>Modelo<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})} placeholder="Ex.: Gol 1.6"/></label><label>Ano<input value={form.year} onChange={e=>setForm({...form,year:e.target.value})} placeholder="2020/2021"/></label><label>Cor<input value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><label>Quilometragem<input type="number" min="0" value={form.mileage} onChange={e=>setForm({...form,mileage:Number(e.target.value)})}/></label><label className="full">Observações<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-action" onClick={close}>Cancelar</button><button disabled={busy} className="primary-action">{busy?"Salvando...":"Salvar veículo"}</button></div></form></div>}
 </div>}
