-- Remove a integracao anterior e instala o fluxo Mercado Pago.
-- Esta migration preserva licencas e pedidos, mas remove IDs/tabelas do Asaas.

drop function if exists public.link_asaas_subscription(uuid, text, text, date);
drop function if exists public.apply_asaas_payment(text, text, text, text, text, date, timestamptz, jsonb);
drop function if exists public.apply_asaas_subscription(text, text, text, text, jsonb);
drop table if exists public.asaas_webhook_events;

alter table public.licenses drop column if exists asaas_customer_id;
alter table public.licenses drop column if exists asaas_subscription_id;
alter table public.licenses add column if not exists mercadopago_subscription_id text;
alter table public.licenses add column if not exists mercadopago_payment_id text;
alter table public.licenses add column if not exists billing_status text not null default 'pending';
alter table public.licenses add column if not exists last_payment_at timestamptz;
alter table public.licenses add column if not exists next_due_at timestamptz;

create unique index if not exists licenses_mercadopago_subscription_uidx
  on public.licenses (mercadopago_subscription_id)
  where mercadopago_subscription_id is not null;
create unique index if not exists licenses_mercadopago_payment_uidx
  on public.licenses (mercadopago_payment_id)
  where mercadopago_payment_id is not null;
create index if not exists licenses_billing_status_idx on public.licenses (billing_status);

alter table public.orders drop column if exists asaas_checkout_id;
alter table public.orders drop column if exists asaas_subscription_id;
alter table public.orders add column if not exists mercadopago_subscription_id text;
alter table public.orders add column if not exists mercadopago_payment_id text;

create unique index if not exists orders_mercadopago_subscription_uidx
  on public.orders (mercadopago_subscription_id)
  where mercadopago_subscription_id is not null;
create unique index if not exists orders_mercadopago_payment_uidx
  on public.orders (mercadopago_payment_id)
  where mercadopago_payment_id is not null;

create table if not exists public.mercadopago_webhook_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  event_type text not null,
  payment_id text,
  subscription_id text,
  payload jsonb not null default '{}'::jsonb,
  processed_at timestamptz not null default now()
);

alter table public.mercadopago_webhook_events enable row level security;
revoke all on public.mercadopago_webhook_events from anon, authenticated;

-- Mantem o painel master informado sobre a cobranca sem expor credenciais.
create or replace function public.admin_list_licenses(p_seller_password text)
returns json
language plpgsql security definer set search_path = public, extensions
as $$
declare stored text;
begin
  select password_hash into stored from seller_settings where id = 1;
  if stored is null or stored = '' or p_seller_password is null
     or extensions.crypt(p_seller_password, stored) is distinct from stored then
    raise exception 'Senha do vendedor invalida';
  end if;
  return (select coalesce(json_agg(row_to_json(t) order by t.created_at desc), '[]'::json)
    from (
      select l.id, l.key, l.customer_name, l.customer_email, l.max_machines,
             l.status, l.expires_at, l.notes, l.created_at,
             l.mercadopago_subscription_id, l.mercadopago_payment_id,
             l.billing_status, l.last_payment_at, l.next_due_at,
             (select count(*) from activations a where a.license_id = l.id) as activation_count,
             (select coalesce(json_agg(json_build_object(
                'id', a.id, 'machineId', a.machine_id, 'machineName', a.machine_name,
                'activatedAt', a.activated_at, 'lastSeenAt', a.last_seen_at
              ) order by a.last_seen_at desc), '[]'::json)
              from activations a where a.license_id = l.id) as activations
      from licenses l
    ) t);
end $$;

revoke all on function public.admin_list_licenses(text) from public, anon, authenticated;
grant execute on function public.admin_list_licenses(text) to anon;

-- Aplica um pagamento consultado diretamente na API do Mercado Pago.
-- O evento e o ID do pagamento sao idempotentes para impedir prorrogacoes duplicadas.
create or replace function public.apply_mercadopago_payment(
  p_event_id text,
  p_event_type text,
  p_payment_id text,
  p_subscription_id text,
  p_external_reference text,
  p_status text,
  p_status_detail text,
  p_amount numeric,
  p_payment_date timestamptz,
  p_payload jsonb default '{}'::jsonb
)
returns json
language plpgsql security definer set search_path = public
as $$
declare
  ord orders%rowtype;
  lic licenses%rowtype;
  base_date timestamptz;
  new_due timestamptz;
  inserted_id bigint;
  new_license_id uuid;
begin
  if nullif(trim(coalesce(p_event_id, '')), '') is null then
    raise exception 'event_id obrigatorio';
  end if;

  insert into mercadopago_webhook_events(event_id, event_type, payment_id, subscription_id, payload)
  values (p_event_id, coalesce(p_event_type, ''), p_payment_id, p_subscription_id, coalesce(p_payload, '{}'::jsonb))
  on conflict (event_id) do nothing
  returning id into inserted_id;

  if inserted_id is null then
    return json_build_object('ok', true, 'duplicate', true);
  end if;

  if p_payment_id is not null and exists (
    select 1 from orders where mercadopago_payment_id = p_payment_id
  ) then
    return json_build_object('ok', true, 'duplicate', true);
  end if;

  select * into ord
    from orders
   where id::text = nullif(trim(coalesce(p_external_reference, '')), '')
      or mercadopago_subscription_id = nullif(trim(coalesce(p_subscription_id, '')), '')
   order by created_at desc
   limit 1
   for update;

  if ord.id is null then
    return json_build_object('ok', true, 'matched', false);
  end if;

  if upper(coalesce(p_status, '')) = 'APPROVED' then
    if p_amount is not null and abs(p_amount - ord.amount) > 0.01 then
      update orders set status = 'canceled' where id = ord.id;
      return json_build_object('ok', false, 'matched', true, 'reason', 'amount_mismatch');
    end if;

    base_date := greatest(coalesce(ord.expires_at, now()), coalesce(p_payment_date, now()));
    new_due := base_date + interval '1 month';

    if ord.license_id is null then
      insert into licenses (
        key, customer_name, customer_email, max_machines, status, expires_at, notes,
        mercadopago_subscription_id, mercadopago_payment_id, billing_status,
        last_payment_at, next_due_at
      ) values (
        _new_license_key(), ord.customer_name, ord.customer_email, 1, 'active', new_due,
        'Plano ' || initcap(ord.plan) || ' - Mercado Pago',
        nullif(trim(coalesce(p_subscription_id, ord.mercadopago_subscription_id)), ''),
        p_payment_id, 'paid', coalesce(p_payment_date, now()), new_due
      ) returning id into new_license_id;
      update orders
         set status = 'paid', mercadopago_payment_id = p_payment_id,
             paid_at = coalesce(p_payment_date, now()), expires_at = new_due,
             license_id = new_license_id
       where id = ord.id;
    else
      select * into lic from licenses where id = ord.license_id for update;
      update licenses
         set status = 'active',
             expires_at = new_due,
             mercadopago_subscription_id = coalesce(nullif(trim(coalesce(p_subscription_id, '')), ''), mercadopago_subscription_id),
             mercadopago_payment_id = p_payment_id,
             billing_status = 'paid',
             last_payment_at = coalesce(p_payment_date, now()),
             next_due_at = new_due
       where id = ord.license_id;
      update orders
         set status = 'paid', mercadopago_payment_id = p_payment_id,
             paid_at = coalesce(p_payment_date, now()), expires_at = new_due
       where id = ord.id;
    end if;
  elsif upper(coalesce(p_status, '')) in ('REJECTED', 'CANCELLED', 'REFUNDED', 'CHARGED_BACK') then
    update orders set status = 'canceled' where id = ord.id and license_id is null;
    if ord.license_id is not null then
      update licenses set status = 'revoked', billing_status =
        case when upper(coalesce(p_status, '')) in ('REFUNDED', 'CHARGED_BACK') then 'canceled' else 'overdue' end
       where id = ord.license_id;
    end if;
  end if;

  return json_build_object('ok', true, 'matched', true, 'licenseId', ord.license_id);
end $$;

revoke all on function public.apply_mercadopago_payment(text, text, text, text, text, text, text, numeric, timestamptz, jsonb)
  from public, anon, authenticated;
grant execute on function public.apply_mercadopago_payment(text, text, text, text, text, text, text, numeric, timestamptz, jsonb)
  to service_role;

create or replace function public.apply_mercadopago_subscription(
  p_event_id text,
  p_event_type text,
  p_subscription_id text,
  p_external_reference text,
  p_status text,
  p_payload jsonb default '{}'::jsonb
)
returns json
language plpgsql security definer set search_path = public
as $$
declare
  inserted_id bigint;
  ord orders%rowtype;
begin
  insert into mercadopago_webhook_events(event_id, event_type, subscription_id, payload)
  values (p_event_id, coalesce(p_event_type, ''), p_subscription_id, coalesce(p_payload, '{}'::jsonb))
  on conflict (event_id) do nothing
  returning id into inserted_id;
  if inserted_id is null then return json_build_object('ok', true, 'duplicate', true); end if;

  select * into ord from orders
   where mercadopago_subscription_id = p_subscription_id
      or id::text = nullif(trim(coalesce(p_external_reference, '')), '')
   order by created_at desc limit 1 for update;
  if ord.id is null then return json_build_object('ok', true, 'matched', false); end if;

  update orders set mercadopago_subscription_id = p_subscription_id where id = ord.id;
  if upper(coalesce(p_status, '')) in ('CANCELLED', 'PAUSED') and ord.license_id is not null then
    update licenses set status = 'revoked', billing_status = 'canceled' where id = ord.license_id;
  end if;
  return json_build_object('ok', true, 'matched', true);
end $$;

revoke all on function public.apply_mercadopago_subscription(text, text, text, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.apply_mercadopago_subscription(text, text, text, text, text, jsonb)
  to service_role;
